### ISSUE TITLE
cluster_update Handler Failures

### ISSUE THREAD

**Issue by remear** [crate/crate-operator#460]
Given a minikube cluster created with `minikube start --cpus=4 --kubernetes-version=v1.23.2`
And the latest crate-operator image
And I’ve also had to set `CRATEDB_OPERATOR_TESTING: true` to bypass the `podAntiAffinity` rules (otherwise the cluster will not come up on a single-node minikube cluster)
And I apply a cluster config of:
 
```yaml
apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: cool-cluster
  namespace: ns-team-launch-dev
spec:
  cluster:
    imageRegistry: crate
    name: crate-dev
    version: 4.7.0
  nodes:
    data:
    - name: hot
      replicas: 3
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        disk:
          count: 1
          size: 5GiB
          storageClass: standard
        heapRatio: 0.5
```
 
The operator logs show the following:

```
[2023-01-26 20:59:17,737] kopf.activities.star [INFO    ] Activity 'startup' succeeded.
[2023-01-26 20:59:17,738] kopf._core.engines.a [INFO    ] Initial authentication has been initiated.
[2023-01-26 20:59:17,738] kopf.activities.auth [INFO    ] Authenticating with in-cluster config
[2023-01-26 20:59:17,739] kopf.activities.auth [INFO    ] Activity 'login' succeeded.
[2023-01-26 20:59:17,739] kopf._core.engines.a [INFO    ] Initial authentication has finished.
[2023-01-26 20:59:59,646] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_create/sql_exporter_config' succeeded.
[2023-01-26 20:59:59,769] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_create/system_user' succeeded.
[2023-01-26 20:59:59,907] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_create/services' succeeded.
[2023-01-26 21:00:00,019] kopf.objects         [WARNING ] [dev/cool-cluster] Deploying cluster cool-cluster without any pod anti-affinity!
[2023-01-26 21:00:00,020] kopf.objects         [WARNING ] [dev/cool-cluster] Deploying cluster cool-cluster without any pod topology spread!
[2023-01-26 21:00:00,020] kopf.objects         [WARNING ] [dev/cool-cluster] Deploying cluster cool-cluster without any tolerations!
[2023-01-26 21:00:00,041] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_create/statefulset_data_hot' succeeded.
[2023-01-26 21:00:00,153] kopf.objects         [INFO    ] [dev/cool-cluster] Webhooks not configured. Not processing event WebhookEvent.FEEDBACK.
[2023-01-26 21:00:00,162] kopf.objects         [INFO    ] [dev/cool-cluster] Trying to create system user ...
[2023-01-26 21:00:00,170] kopf.objects         [ERROR   ] [dev/cool-cluster] ... failed. Status: 400 Message: Invalid response status
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/crate/operator/bootstrap.py", line 186, in bootstrap_system_user
    result = await core_ws.connect_get_namespaced_pod_exec(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 182, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/stream/ws_client.py", line 78, in request
    async with self.rest_client.pool_manager.ws_connect(url, headers=headers) as ws:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 400, message='Invalid response status', url=URL('wss://10.96.0.1:443/api/v1/namespaces/dev/pods/crate-data-hot-cool-cluster-0/exec?command=crash&command=--verify-ssl%3Dfalse&command=--host%3Dhttp://localhost:4200&command=-c&command=CREATE+USER+%22system%22+WITH+(password%3D'4N4iAaxwfbI8SIoszQYO6gmO9SKqdUDTtu6K8nM4HRh3WjvK6z')%3B&container=crate&stderr=True&stdin=False&stdout=True&tty=False')
[2023-01-26 21:00:00,172] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_create/bootstrap' failed temporarily: None
[2023-01-26 21:01:00,297] kopf.objects         [INFO    ] [dev/cool-cluster] Webhooks not configured. Not processing event WebhookEvent.FEEDBACK.
[2023-01-26 21:01:00,307] kopf.objects         [INFO    ] [dev/cool-cluster] Trying to create system user ...
[2023-01-26 21:01:00,327] kopf.objects         [ERROR   ] [dev/cool-cluster] ... failed. Status: 500 Message: Invalid response status
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/crate/operator/bootstrap.py", line 186, in bootstrap_system_user
    result = await core_ws.connect_get_namespaced_pod_exec(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 182, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/stream/ws_client.py", line 78, in request
    async with self.rest_client.pool_manager.ws_connect(url, headers=headers) as ws:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 500, message='Invalid response status', url=URL('wss://10.96.0.1:443/api/v1/namespaces/dev/pods/crate-data-hot-cool-cluster-0/exec?command=crash&command=--verify-ssl%3Dfalse&command=--host%3Dhttp://localhost:4200&command=-c&command=CREATE+USER+%22system%22+WITH+(password%3D'4N4iAaxwfbI8SIoszQYO6gmO9SKqdUDTtu6K8nM4HRh3WjvK6z')%3B&container=crate&stderr=True&stdin=False&stdout=True&tty=False')
[2023-01-26 21:01:00,328] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_create/bootstrap' failed temporarily: None
[2023-01-26 21:02:00,456] kopf.objects         [INFO    ] [dev/cool-cluster] Webhooks not configured. Not processing event WebhookEvent.FEEDBACK.
[2023-01-26 21:02:00,466] kopf.objects         [INFO    ] [dev/cool-cluster] Trying to create system user ...
[2023-01-26 21:02:02,074] kopf.objects         [INFO    ] [dev/cool-cluster] ... success
[2023-01-26 21:02:02,075] kopf.objects         [INFO    ] [dev/cool-cluster] Trying to grant system user all privileges ...
[2023-01-26 21:02:02,345] kopf.objects         [INFO    ] [dev/cool-cluster] ... success
[2023-01-26 21:02:02,346] kopf.objects         [INFO    ] [dev/cool-cluster] Webhooks not configured. Not processing event WebhookEvent.FEEDBACK.
[2023-01-26 21:02:02,347] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_create/bootstrap' succeeded.
[2023-01-26 21:02:02,347] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_create' succeeded.
[2023-01-26 21:02:02,347] kopf.objects         [INFO    ] [dev/cool-cluster] Creation is processed: 1 succeeded; 0 failed.
```

After creation reports as successful, I deploy an update to the cluster, e.g., updating the crate version or increasing the node CPU limits and see the following:

``` 
[2023-01-26 21:03:14,193] kopf.objects         [INFO    ] [dev/cool-cluster] Handler 'cluster_update/before_cluster_update/disable_cronjob' succeeded.
[2023-01-26 21:03:14,312] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_update/change_compute' failed temporarily: Waiting for 'cluster_update/before_cluster_update'.
[2023-01-26 21:03:14,423] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_update/restart' failed temporarily: Waiting for 'cluster_update/before_cluster_update,cluster_update/change_compute'.
[2023-01-26 21:03:14,533] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_update/after_change_compute' failed temporarily: Waiting for 'cluster_update/before_cluster_update,cluster_update/change_compute,cluster_update/restart'.
[2023-01-26 21:03:14,644] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_update/after_cluster_update' failed temporarily: Waiting for 'cluster_update/before_cluster_update,cluster_update/change_compute,cluster_update/restart,cluster_update/after_change_compute'.
[2023-01-26 21:03:14,758] kopf.objects         [ERROR   ] [dev/cool-cluster] Handler 'cluster_update/notify_success_update' failed temporarily: Waiting for 'cluster_update/before_cluster_update,cluster_update/change_compute,cluster_update/restart,cluster_update/after_change_compute,cluster_update/after_cluster_update'.
```
 
Subsequent attempts to update the cluster do nothing and produce no other output.

**Comment by SStorm** [comment]
Hi @remear, could you provide some more logs from the update operation - looks like it is waiting for `before_cluster_update` to complete. That is doing several things, and it looks like one of them might be failing.

**Comment by remear** [comment]
What's the best way to get those additional logs? The logs I shared above were everything I was able to see when tailing the logs for the operator pod for the operator boot, cluster creation, and two attempts at a cluster update.

**Comment by SStorm** [comment]
It would be in the operator pod yes (or alternatively in `kubectl get events` in the namespace where you created your cluster). But if you're saying that's everything, then I'll try to reproduce locally and get back to you.

**Comment by SStorm** [comment]
Did not manage to reproduce, closing as stale.
