### ISSUE TITLE
Issue with elasticsearch exception

### ISSUE THREAD

**Issue by etiennejournet** [crate/crate-operator#514]
Hello Team ! 

I've got an issue with the db not launching, here is the error message : 
```[2023-05-12T09:11:36,286][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [data-my-cluster-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:30) ~[crate-app.jar:4.8.1]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:162) ~[crate-app.jar:4.8.1]
	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) ~[crate-app.jar:4.8.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[crate-server.jar:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[crate-cli.jar:?]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[crate-cli.jar:?]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) ~[crate-app.jar:4.8.1]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) ~[crate-app.jar:4.8.1]
Caused by: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:185) ~[crate-server.jar:?]
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:214) ~[crate-server.jar:?]
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:188) ~[crate-server.jar:?]
	at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:107) ~[crate-server.jar:?]
	at io.crate.protocols.postgres.PostgresNetty.resolveBindAddress(PostgresNetty.java:231) ~[crate-server.jar:?]
	at io.crate.protocols.postgres.PostgresNetty.doStart(PostgresNetty.java:196) ~[crate-server.jar:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:60) ~[crate-server.jar:?]
	at org.elasticsearch.node.Node.start(Node.java:879) ~[crate-server.jar:?]
	at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:204) ~[crate-app.jar:4.8.1]
	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:268) ~[crate-app.jar:4.8.1]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) ~[crate-app.jar:4.8.1]
	... 6 more
```

I'm using this manifest : 
```apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: cluster-test
spec:
  cluster:
    imageRegistry: crate
    name: crate-test
    version: "4.8.1"
  nodes:
    data:
    - name: my-cluster
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        disk:
          count: 1
          size: 128GiB
          storageClass: managed-csi
        heapRatio: 0.25
```

And this operator config : 
```
env:
  CRATEDB_OPERATOR_CLOUD_PROVIDER: azure
  CRATEDB_OPERATOR_BOOTSTRAP_TIMEOUT: "1800"
  CRATEDB_OPERATOR_DEBUG_VOLUME_SIZE: "128GiB"
  CRATEDB_OPERATOR_DEBUG_VOLUME_STORAGE_CLASS: "default"
  CRATEDB_OPERATOR_JMX_EXPORTER_VERSION: "1.0.0"
  CRATEDB_OPERATOR_LOG_LEVEL: "INFO"
  CRATEDB_OPERATOR_ROLLING_RESTART_TIMEOUT: "3600"
  CRATEDB_OPERATOR_SCALING_TIMEOUT: "3600"
```

I tried adding the env variable : `NETWORK_HOST` with some values (_local_, lo), outlined by a Google search, as I was really clueless ... 

Also, the Pod doesn't crash so I guess it misses a liveness probe ?

Thanks for your help :)

**Comment by SStorm** [comment]
Hi @etiennejournet, it looks like a networking issue in your Kubernetes setup. When you launch a pod (CrateDB or otherwise), what network interfaces you get (`ifconfig`)?

**Comment by etiennejournet** [comment]
Hello @SStorm 

New Pod :
```
$ k run -ti --image=alpine:latest test -- sh
If you don't see a command prompt, try pressing enter.
/ # ifconfig
eth0      Link encap:Ethernet  HWaddr E6:C8:BC:AC:77:06  
          inet addr:100.64.0.77  Bcast:0.0.0.0  Mask:255.192.0.0
          inet6 addr: fe80::e4c8:bcff:feac:7706/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:788 (788.0 B)  TX bytes:488 (488.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
Crate Pod :
```
$ k exec -ti crate-data-my-cluster-cluster-test-0 -c crate -- sh
sh-4.2# yum install net-tools
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: miroir.univ-lorraine.fr
 * extras: miroir.univ-lorraine.fr
 * updates: mirrors.ircam.fr
Package net-tools-2.0-0.25.20131004git.el7.x86_64 already installed and latest version
Nothing to do
sh-4.2# ifconfig
eth0: flags=67<UP,BROADCAST,RUNNING>  mtu 1500
        inet 100.64.0.83  netmask 255.192.0.0  broadcast 0.0.0.0
        inet6 fe80::a0d9:2eff:fe52:32e8  prefixlen 64  scopeid 0x20<link>
        ether a2:d9:2e:52:32:e8  txqueuelen 1000  (Ethernet)
        RX packets 17670  bytes 30349730 (28.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10704  bytes 808629 (789.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1144  bytes 68640 (67.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1144  bytes 68640 (67.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by etiennejournet** [comment]
I just tested with the helm chart (not the operator but the single instance), using `--set image.tag=4.8.1` and it works.

**Comment by etiennejournet** [comment]
Here is the solution : 

```
$ k get -o yaml sts crate-data-my-cluster-cluster-test | yq '.spec.template.spec.containers.1.command'
- /docker-entrypoint.sh
- crate
- -Cstats.enabled=true
- -Ccluster.name=crate-test
- -Cnode.name=data-my-cluster-$(hostname | rev | cut -d- -f1 | rev)
- -Ccluster.initial_master_nodes=data-my-cluster-0
- -Cdiscovery.seed_providers=srv
- -Cdiscovery.srv.query=_cluster._tcp.crate-discovery-cluster-test.default.svc.cluster.local
- -Cgateway.recover_after_data_nodes=1
- -Cgateway.expected_data_nodes=1
- -Cnetwork.host=0.0.0.0 ##### **network.host should be added here** 
- -Cauth.host_based.enabled=true
- -Cauth.host_based.config.0.user=crate
- -Cauth.host_based.config.0.address=_local_
- -Cauth.host_based.config.0.method=trust
- -Cauth.host_based.config.99.method=password
- -Cpath.data=/data/data0
- -Cprocessors=1
- -Cnode.master=true
- -Cnode.data=true
- -Cnode.attr.node_name=my-cluster
- '-Cnode.attr.zone=$(curl -s ''http://169.254.169.254/metadata/instance/compute/zone?api-version=2020-06-01&format=text'' -H ''Metadata: true'')
```
